name: 'Terraform Setup'
description: 'Configura ambiente Terraform com AWS'

inputs:
  aws-role-arn:
    description: 'ARN da role AWS para assumir'
    required: true

runs:
  using: "composite"
  steps:      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: sa-east-1
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0